name: Build Backend Image on Merge Group

on:
  pull_request:
    branches: [ "main" ]
  merge_group:
    types: [checks_requested]

env:
  REGISTRY_IMAGE: danswer/danswer-backend

jobs:
  build:
    # TODO: make this a matrix build like the web containers
    runs-on: 
      group: amd64-image-builders
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Backend Image Docker Build
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: |
          ${{ env.REGISTRY_IMAGE }}:latest
        build-args: |
          DANSWER_VERSION=v0.0.1
